/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as token from "./token";
export { MyVaultTokenERC20__factory } from "./MyVaultTokenERC20__factory";
export { MyVaultTokenERC4626__factory } from "./MyVaultTokenERC4626__factory";
