/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { MyVaultTokenERC4626 } from "./MyVaultTokenERC4626";
export type { VaultTokenERC4626 } from "./VaultTokenERC4626";
